### PR TITLE
Fix isNormalized for field selections

### LINKED ISSUE #1209: Test failure in "isNormalized should be consistent with normalize"
```
    isNormalized should be consistent with normalize:                                                                          FAIL (0.61s)
      *** Failed! Falsifiable (after 1801 tests and 2 shrinks):
      Field (Prefer (RecordLit (fromList [("",OptionalFold)])) (RecordLit (fromList []))) ""
      True /= False
      Use --quickcheck-replay=139427 to reproduce.
```

Reported in #1208. I'll try to make a fix.

### PR DESCRIPTION
**Pull request by sjakobi**
In expressions like

    ({ x : Optional/fold } // {=}).x

`isNormalized` didn't check if the expression being selected from
was normalized.

Fixes #1209.

### CODE REVIEW

File: dhall/src/Dhall/Core.hs [hunk 1]
```diff
@@ -2013,9 +2013,9 @@ isNormalized e0 = loop (denote e0)
       Field r k -> case r of
           RecordLit _ -> False
           Project _ _ -> False
-          Combine x@(RecordLit m) y -> loop x && loop y && Dhall.Map.member k m
-          Combine x (RecordLit m) -> loop x && Dhall.Map.toList (fmap loop m) == [(k, True)]
-          Prefer x@(RecordLit m) y -> loop x && loop y && Dhall.Map.member k m
+          Combine (RecordLit m) _ -> Dhall.Map.member k m && loop r
```
Comment (Gabriel439) [inline dhall/src/Dhall/Core.hs]: Perhaps move  the `loop r` check above so that does not have to be repeated across the branches, like this:

```haskell
Field r k -> loop r && case r of
    RecordLit _ -> False
    …
```

Comment (sjakobi) [reply dhall/src/Dhall/Core.hs]: I actually did that in a previous version of this fix, but I just couldn't handle the inefficiency! ;)

If you don't mind too much I'd slightly prefer to keep the fix as it is now.

Comment (Gabriel439) [reply dhall/src/Dhall/Core.hs]: I don't mind!  It was just a suggestion :slightly_smiling_face:
