### PR TITLE
fix(label-formatting): quoted labels reserved keywords should have quoted in `dhall format` output

### LINKED ISSUE #1805: Labels that are keywords should be quoted
```
$ echo '{ `if` = 0 }' | dhall
{ if = 0 }
```

`if` (unquoted) is not a valid label.

`Some` will need special treatment: Only when used as a record label can it remain unquoted.

### PR DESCRIPTION
**Pull request by german1608**
# Summary

Fixes #1805 

# Solution

Amend `escapeLabel` to quote reserved keywords, except for `Some`.

# Tests

I added two tests:

- `issue1805KeywordRecordFieldShouldBeQuoted`
- `issue1805SomeQuotedInLetButNotInRecord`

in the `format` tests directory. Although their A.dhall and B.dhall are the same, I left them to ensure quoting on keyword as labels.

### CODE REVIEW

File: dhall/src/Dhall/Pretty/Internal.hs [hunk 1]
```diff
@@ -439,9 +439,12 @@ escapeLabel :: Bool -> Text -> Text
 escapeLabel allowReserved l =
     case Text.uncons l of
         Just (h, t)
-            | headCharacter h && Text.all tailCharacter t && (allowReserved || not (Data.HashSet.member l reservedIdentifiers))
+            | headCharacter h && Text.all tailCharacter t && someOrNotLanguageKeyword && (allowReserved || notReservedIdentifier)
```
Comment (Gabriel439) [inline dhall/src/Dhall/Pretty/Internal.hs:442]: You can make this check more efficient by refactoring it to:

```haskell
| headCharacter h
    &&  Text.all tailCharacter t
    &&  (   not (member l reservedIdentifiers)
        ||  (allowReserved && (not (member l reservedKeywordsExceptSome)))
        )
```

... that way the vast majority of the time `escapeLabel` function doesn't need to check whether `allowReserved` is `True` or not

Comment (german1608) [reply dhall/src/Dhall/Pretty/Internal.hs:442]: In some moment we may need a refactor for special handling of `Some`, in case that in the future another keyword requires that special treatment as well.

**Comment by sjakobi** [comment]
Thanks @german1608! :)
