### PR TITLE
Interpolate leading whitespace on the last line of a multi-line string 

### LINKED ISSUE #1545: Incorrect formatting of multi-line strings with leading whitespace
Strings where the last line starts with whitespace are currently incorrectly formatted as multi-line strings:

```
$ echo '"\n\tx"' | dhall format
''

	x''
$ echo '"\n\tx"' | dhall format | dhall format
''

x''
```

```
$ echo '"\n x"' | dhall format
''

 x''
$ echo '"\n x"' | dhall format | dhall format
''

x''
```

I discovered this bug by running the very powerful formatting idempotence test while I was working on https://github.com/dhall-lang/dhall-haskell/pull/1543. @Gabriel439 pointed out that the underlying reason lies in the multi-line string dedentation logic specified in https://github.com/dhall-lang/dhall-lang/blob/master/standard/multiline.md#indentation.

This should be fixed by formatting such strings on a single line. I'm currently working on a patch.

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #1545.

Includes #1543.

### CODE REVIEW

File: dhall/src/Dhall/Pretty/Internal.hs [hunk 1]
```diff
@@ -1072,21 +1072,23 @@ prettyCharacterSet characterSet expression =
         angles . map prettyAlternative . Dhall.Map.toList
 
     prettyChunks :: Pretty a => Chunks Src a -> Doc Ann
-    prettyChunks (Chunks a b) =
-        if anyText (== '\n')
-        then
-            if anyText (/= '\n')
+    prettyChunks chunks@(Chunks a b)
+        | anyText (== '\n') =
+            if not (null a) || anyText (/= '\n')
```
Comment (Gabriel439) [inline dhall/src/Dhall/Pretty/Internal.hs]: My understanding is that if `anyText (== '\n')` is `True` then `not (null a)` always evaluates to `True`, therefore the second branch of this `if` expression becomes dead code

File: dhall/src/Dhall/Pretty/Internal.hs [hunk 2]
```diff
@@ -1121,6 +1123,94 @@ prettyCharacterSet characterSet expression =
...
+-- character sequences.
+--
+-- >>> multilineChunks (Chunks [] "\n \tx")
+-- Chunks [("\n",TextLit (Chunks [] " \t"))] "x"
+-- >>> multilineChunks (Chunks [] "\n\NUL\b\f\t")
+-- Chunks [("\n",TextLit (Chunks [] "\NUL\b\f"))] "\t"
+multilineChunks :: Chunks s a -> Chunks s a
+multilineChunks = interpolateControlCharacters . interpolateLastLineLeadingWhitespace
+
+-- | Interpolate leading whitespace on the last line
```
Comment (Gabriel439) [inline dhall/src/Dhall/Pretty/Internal.hs]: Why only on the last line?  My understanding is that you would need to interpolate leading whitespace for all lines.  In other words, for a double-quoted string like this:

```dhall
" \n\t\n"
```

... you would have to emit:

```dhall
${" "}
${"\t"}
```

File: dhall/src/Dhall/Pretty/Internal.hs (hunk 1 above)
Comment (sjakobi) [reply dhall/src/Dhall/Pretty/Internal.hs]: Not quite: For example in the case of `Chunks [] "\n"`, `anyText (== '\n')` is `True`, but `not (null a)` is `False` (a is `[]`).

This additional condition was necessary to fix idempotence:

    Formatting should be idempotent: FAIL (6.63s)
      *** Failed! Falsifiable (after 1534 tests and 2 shrinks):
      Unicode
      Header ""
      TextLit (Chunks [] "\n ")
      "''\n\n${\" \"}''\n" /= "\"\\n${\" \"}\"\n"
      Use --quickcheck-replay=854885 to reproduce.

Should I add a comment?

File: dhall/src/Dhall/Pretty/Internal.hs (hunk 2 above)
Comment (sjakobi) [reply dhall/src/Dhall/Pretty/Internal.hs]: We could do that but it doesn't seem to be necessary. In my (possibly incorrect) understanding of the dedentation rules, the whitespace on all but the last line is "protected" by the indentation level of the opening `''`. Only the leading whitespace on the very last line is ignored by the parser.


Aside: I wonder whether we should change the parser (and the standard?) to keep the whitespace on the last line in the case of

```dhall
''

  x''
```

and to only ignore it when the last is all whitespace, e.g.

```dhall
''

  ''
```

Comment (Gabriel439) [reply dhall/src/Dhall/Pretty/Internal.hs]: @sjakobi: You're assuming that the string literal came from parsing a multi-line literal.  I'm talking about a situation where the user enters a double-quoted literal with newlines and each line is preceded by trailing whitespace.

Comment (sjakobi) [reply dhall/src/Dhall/Pretty/Internal.hs]: Oof, this stuff is confusing! :/

In any case, we can already handle your example fine on `master` – the whitespace is preserved:

```
$ echo '" \n\t\n"' | dhall
''
 
	
''
$ echo '" \n\t\n"' | dhall | dhall
''
 
	
''
Is this what you mean?

Comment (Gabriel439) [reply dhall/src/Dhall/Pretty/Internal.hs]: @sjakobi: That particular example works because the leading whitespace is different, but now consider this case:

```dhall
" \n \n"
```

... or equivalently:

```dhall
''
${" "}
${" "}
''
```

Comment (sjakobi) [reply dhall/src/Dhall/Pretty/Internal.hs]: I don't get it – we're already handling this fine:

```
$ echo '" \\n \\n"' | dhall
''
 
 
''
$ echo '" \\n \\n"' | dhall | dhall
''
 
 
''
```

Comment (Gabriel439) [reply dhall/src/Dhall/Pretty/Internal.hs]: @sjakobi: Oh, my mistake.  Now I see why you need to give the last line special treatment.  Ignore me, then! 🙂

Comment (sjakobi) [reply dhall/src/Dhall/Pretty/Internal.hs]: No worries @Gabriel439! I definitely don't understand the multi-line string spec 100%.

**Comment by sjakobi** [comment]
Ha, I think _now_ I understand it too! :blush:

Notably it's not actually necessary to escape the leading whitespace on the last line if at least one other line starts with a non-whitespace character or an interpolation.

However I think it's reasonable to escape the whitespace anyway, since otherwise it might easily be removed accidentally by editing a different line…
