### PR TITLE
Report input name in parsing errors

### LINKED ISSUE #2194: Errors do not specify which file they occur in when multiple files are passed to a subcommand
#2169 was great and allows one to pass multiple files at once to e.g. `dhall freeze`.  However, currently no information about *which* file fails is output to the user, making it very difficult to track down the problem if many files are passed.

For example:

```bash
echo 0 > a.dhall 

echo 0f > b.dhall

dhall freeze a.dhall b.dhall
dhall: 
Error: Invalid input

(input):1:2:
  |
1 | 0f
  |  ^
unexpected 'f'
expecting "→", "∧", "⩓", "⫽", ->, //, //\\, /\, :, end of input, keyword, operator, or whitespace
```

If instead the error were output as:

```bash
dhall: 
Error: Invalid input

(./b.dhall):1:2:
  |
1 | 0f
  |  ^
unexpected 'f'
expecting "→", "∧", "⩓", "⫽", ->, //, //\\, /\, :, end of input, keyword, operator, or whitespace
```

or something instead of just `(input)` it would be much more clear.

This also occurs with e.g. `dhall lint`

As such, I've been unable to use the new multi-file commands in my CI and am stuck doing something like:

```bash
for n; do echo "$n"; dhall lint --check "$n" || exit 1; done
```

which of course still works but it would be great to use the new option to process multiple files at once, since it's currently a pain to track down what the issue is if you're linting 500 files at once.  :smile:

### PR DESCRIPTION
**Pull request by basile-henry**
Fixes #2194

Parser errors in `format`, `freeze`, `lint` didn't report which input they came from. This wasn't an issue until we started supporting multiple inputs.

### CODE REVIEW

File: dhall/src/Dhall/Util.hs [hunk 1]
```diff
@@ -149,7 +149,11 @@ data Censor = NoCensor | Censor
 data Input = StandardInput | InputFile FilePath deriving (Eq)
 
 -- | Path to input or raw input text, necessary since we can't read STDIN twice
-data InputOrTextFromStdin = Input_ Input | StdinText Text
+data InputOrTextFromStdin
+    = Input_ Input
+    | StdinText String Text
+    -- ^ StdinText name text where name is a use-friendly name describing the
```
Comment (basile-henry) [inline dhall/src/Dhall/Util.hs:155]:
```suggestion
    -- ^ @StdinText name text@ where name is a user-friendly name describing the
```

**Review by TristanCacqueray — APPROVED** [review]
Thanks, that is looking good to me.

**Comment by Gabriel439** [comment]
@basile-henry: Thank you for fixing that! 🙂

**Review by SiriusStarr — COMMENTED** [review]
LGTM!  Thanks for the quick fix.  :-)
