### PR TITLE
Use System.Directory to get cache dirs

### LINKED ISSUE #549: Cache imports not working in windows by default
Hi, i've tested the [new feature of cache imports](https://github.com/dhall-lang/dhall-haskell/commit/d010464d02836025251b2d061fe93b56625daa3b) using in master version and it seems that it is not working in (at least some versions) of windows.
In Windows 7 the `HOME` environment variable used in the code is not set by default, the more similar one would be `%USERPROFILE%`. 
Setting `HOME` at system configuration level makes it work but no setting it in the dos console.

### PR DESCRIPTION
**Pull request by jneira**
To fix #549

### CODE REVIEW

**Comment by jneira** [comment]
In Windows it picks for xdg cache dir  `%LOCALAPPDATA%`(`C:\Users\user\AppData\Local`)

File: src/Dhall/Import.hs [hunk 1]
```diff
@@ -540,13 +540,14 @@ getCacheFile hash = do
...
 
     let tryXdgCacheHome = do
-            Just cacheDirectory <- liftIO (System.Environment.lookupEnv "XDG_CACHE_HOME")
+            cacheDirectory <- liftIO $ Directory.getXdgDirectory Directory.XdgCache ""
+            
             assertDirectory cacheDirectory
 
             return cacheDirectory
 
     let tryHome = do
```
Comment (Gabriel439) [inline src/Dhall/Import.hs]: @jneira: You can delete the `tryHome` alternative since `Directory.getXdgDirectory` already falls back to `~/.cache` if the `XDG_CACHE_HOME` environment variable is unset

File: src/Dhall/Import.hs [hunk 2]
```diff
@@ -539,26 +539,13 @@ getCacheFile hash = do
 
                     liftIO (Directory.setPermissions directory private)
 
-    let tryXdgCacheHome = do
+    cacheDirectory <- do
```
Comment (Gabriel439) [inline src/Dhall/Import.hs]: You can also simplify this a bit further by inlining the inner `do` block into the outer `do` block.  In other words, instead of this:

```haskell
cacheDirectory <- do
    cacheDirectory <- liftIO $ Directory.getXdgDirectory Directory.XdgCache ""

    assertDirectory cacheDirectory

    return cacheDirectory
```

... you can do this:

```haskell
cacheDirectory <- liftIO $ Directory.getXdgDirectory Directory.XdgCache ""

assertDirectory cacheDirectory
```

Comment (jneira) [reply src/Dhall/Import.hs]: yeah, the nesting do is unnecesary

**Comment by Gabriel439** [comment]
Thanks for doing this! 🙂
