### PR TITLE
Fix: `Text` values that represents boolean values in YAML 1.1 are quoted

### LINKED ISSUE #1785: Escape dhall 'Text' variables with boolean values in YAML
Hi, thanks for working on Dhall and all the awesome ecosystem!

We're using Dhall in Relude to generate thousands of lines of custom HLint suggestions from a much smaller Dhall config. However, I've started to have a problem when using `dhall-json-1.6.4` (the latest version). We reexport Haskell function with the name `on`, which, IIUC, parses as the boolean value `true` in YAML. As a consequence, this results in the following HLint error when I'm trying to use the generated config:

```
hlint: user error (Failed to read YAML configuration file /home/shersh/haskell/kowainik/relude/.hlint.yaml
  Aeson exception:
Error in $: Error when decoding YAML, Expected a String
Along path: root 479 warn rhs
When at: Bool
warn:
  lhs: Data.Function.on
  note: '''on'' is already exported from Relude'
  name: Use 'on' from Relude
  rhs: true
)
```

This started to happen after an attempt to use the latest version of `dhall-json`. Here is the diff for the relevant YAML piece:

```diff
 - warn:
     lhs: Data.Function.on
-    note: '''on'' is already exported from Relude'
-    name: Use 'on' from Relude
-    rhs: 'on'
+    name: "Use 'on' from Relude"
+    note: "'on' is already exported from Relude"
+    rhs: on
```

When I tried to replace the string `"on"` in my Dhall config with `"\"on\""`, I got the same string in the HLint config, which is also incorrect, so I don't see a way to work around this issue at the moment except removing this particular warning from `relude` (which is undesirable, as you can understand).

### PR DESCRIPTION
**Pull request by german1608**
Fixes #1785 

## Solution
The `Text` values that matches with the regex described on [Yaml 1.1](https://yaml.org/type/bool.html) specs are quoted so yaml 1.1 parsers doesn't parses them as boolean values

## Notes

`dhall-yaml` module uses HsYaml which let us set a custom encoding on each value, which fixes the issue for `dhall-to-yaml-ng` command.

Sadly, `dhall-json` source code for `dhall-to-yaml` command uses aeson-yaml, which doesn't provide a way to set custom encodings: only quoted or unquoted.

I suggest that `dhall-to-yaml` users that encounters this issue to use the `--quoted` flag to quote all key/values in yaml output or to move to `dhall-to-yaml-ng`

Another thing that should be noted is that not only values that match the boolean regex of specs are encoded, but also keys. So,

```dhall
{ yes = "hi" }
```
is encoded to

```yaml
'yes': hi
```

### CODE REVIEW

**Comment by german1608** [comment]
This was encoding before this PR:
```yaml
- warn:
    lhs: Data.Function.on
    name: "Use 'on' from Relude"
    note: "'on' is already exported from Relude"
    rhs: on
```

This is the fix introduced:

```yaml
- warn:
    lhs: Data.Function.on
    name: "Use 'on' from Relude"
    note: "'on' is already exported from Relude"
    rhs: 'on'
```

File: dhall-yaml/tasty/Main.hs [hunk 1]
```diff
@@ -30,28 +30,48 @@ testTree =
...
-testDhallToYaml options prefix =
-    Test.Tasty.testGroup prefix
-        [ testCase Dhall.Yaml.dhallToYaml "HsYAML"
-        , testCase Dhall.JSON.Yaml.dhallToYaml "aeson-yaml"
-        ]
+testDhallToYaml :: Options -> String -> Bool -> Bool -> TestTree
+testDhallToYaml options prefix testHsYaml testAesonYaml =
+    Test.Tasty.testGroup prefix (
+        [testCase Dhall.Yaml.dhallToYaml "HsYAML" | testHsYaml] <>
+        [testCase Dhall.JSON.Yaml.dhallToYaml "aeson-yaml" | testAesonYaml]
```
Comment (sjakobi) [inline dhall-yaml/tasty/Main.hs:73]: Even better than _skipping_ one of the tools would be to check that it fails, using `tasty-expected-failure`. That way, we could be sure that the two tools actually behave differently.

We already have a bit of tooling around `tasty-expected-failure` in the `dhall` testsuite – maybe we can reuse that here.

File: dhall-yaml/src/Dhall/Yaml.hs [hunk 2]
```diff
@@ -51,26 +52,22 @@ jsonToYaml
...
+    _ -> Data.ByteString.Lazy.toStrict (encoder [json])
   where
     style (Y.SStr s)
         | "\n" `Text.isInfixOf` s =
             Right (YE.untagged, YE.Literal YE.Clip YE.IndentAuto, s)
         | quoted || Text.all isNumberOrDateRelated s || isBoolString =
             Right (YE.untagged, YE.SingleQuoted, s)
       where
-        isBoolString
-          | Text.length s > 5 = False
```
Comment (patrickmn) [inline dhall-yaml/src/Dhall/Yaml.hs:68]: This check was to prevent doing `Text.toLower` unnecessarily.

**Comment by patrickmn** [comment]
This is actually exactly what aeson-yaml used to do:

https://github.com/clovyr/aeson-yaml/commit/3441232a5dbe6ee0fe7e0e465608cea87c662891

These YAML 1.1 <-> 1.2 compatibility hacks were causing their own issues and bug reports for "unnecessary quoting" from people using newer parsers, and I kept reading that you explicitly shouldn't treat those on/off/ON/OFF/yes/no as bools anymore, so I took them out ☹️ 

https://stackoverflow.com/questions/42283732/are-on-and-off-supposed-to-be-interpreted-as-true-or-false-in-yaml-1-2

I could put it back into aeson-yaml behind some flag that enables 1.1 compat hacks, but this change also seems fine to me, especially given the bool handling we already put in to address the tests failing.

**Comment by patrickmn** [comment]
Btw.

> FYI, @patrickmn, Germán is our GSoC student this summer. His main project will be to work on a documentation generator for Dhall.

a documentation generator for Dhall sounds amazing. I would love to be a part of that project somehow.

**Comment by patrickmn** [comment]
Actual footage of maintaining a YAML library:

File: dhall-yaml/src/Dhall/Yaml.hs [hunk 3]
```diff
@@ -51,26 +52,22 @@ jsonToYaml
...
-          | otherwise =
-            case Text.toLower s of
-              "true" -> True
-              "false" -> True
-              _ -> False
+        -- For backwards compatibility with YAML 1.1, we need to add the following to the set of boolean values:
+        -- https://yaml.org/type/bool.html
+        isBoolString = Text.toLower s `elem` ["y", "yes", "n", "no", "true", "false", "on", "off"]
```
[the remark this answers is not in the document]
Comment (german1608) [reply dhall-yaml/src/Dhall/Yaml.hs:70]: I point out this, but it does'n't hurt to quote those cases. `yEs` is an alias for `'yEs` in both yaml 1.1 and 1.2

File: dhall-yaml/tasty/Main.hs [hunk 4]
```diff
@@ -30,28 +30,48 @@ testTree =
...
         ]
 
-testDhallToYaml :: Options -> String -> TestTree
-testDhallToYaml options prefix =
-    Test.Tasty.testGroup prefix
-        [ testCase Dhall.Yaml.dhallToYaml "HsYAML"
-        , testCase Dhall.JSON.Yaml.dhallToYaml "aeson-yaml"
-        ]
+testDhallToYaml :: Options -> String -> Bool -> Bool -> TestTree
+testDhallToYaml options prefix testHsYaml testAesonYaml =
```
[the remark this answers is not in the document]
Comment (german1608) [reply dhall-yaml/tasty/Main.hs:70]: I actually thought of this, but didn't implement it because these were tests. But I like your last suggestion, so I'm going to do it

File: dhall-json/src/Dhall/DhallToYaml/Main.hs [hunk 5]
```diff
@@ -5,14 +5,15 @@
...
-import Options.Applicative (Parser, ParserInfo)
+import           Control.Applicative (optional, (<|>))
+import           Control.Exception   (SomeException)
+import           Data.ByteString     (ByteString)
+import           Data.Monoid         ((<>))
+import           Data.Text           (Text)
+import           Dhall.JSON          (parseConversion,
+                                      parsePreservationAndOmission)
+import           Dhall.JSON.Yaml     (Options (..), parseDocuments, parseQuoted)
+import           Options.Applicative (Parser, ParserInfo)
```
[the remark this answers is not in the document]
Comment (german1608) [reply dhall-json/src/Dhall/DhallToYaml/Main.hs:16]: Yes! I have a plugin for VScode that does the formatting.

I think that I'll disable my plugin for the moment, but there must be a way to configure stylish-haskell to ignore non-qualified imports spacing.

File: dhall-yaml/tasty/Main.hs (hunk 1 above)
Comment (german1608) [reply dhall-yaml/tasty/Main.hs:73]: I'll check that out!

File: dhall-yaml/src/Dhall/Yaml.hs (hunk 2 above)
Comment (german1608) [reply dhall-yaml/src/Dhall/Yaml.hs:68]: Is `Text.toLower` a really expensive computation?

**Comment by german1608** [comment]
> Btw.
> 
> > FYI, @patrickmn, Germán is our GSoC student this summer. His main project will be to work on a documentation generator for Dhall.
> 
> a documentation generator for Dhall sounds amazing. I would love to be a part of that project somehow.

Sooner than later I'll try to take input from dhall users/developers into what would they expect of that :)

File: dhall-yaml/src/Dhall/Yaml.hs (hunk 2 above)
Comment (patrickmn) [reply dhall-yaml/src/Dhall/Yaml.hs:68]: Not for most **keys**, but this could potentially be a very long value. I benchmarked some common kubernetes payloads with large base64-encoded strings, and the difference when not lowercasing those was noticeable.

Comment (german1608) [reply dhall-yaml/src/Dhall/Yaml.hs:68]: Ok I see. I'll keep that check then

File: dhall-json/src/Dhall/DhallToYaml/Main.hs (hunk 5 above)
[the remark this answers is not in the document]
Comment (german1608) [reply dhall-json/src/Dhall/DhallToYaml/Main.hs]: I added a .stylish-haskell.yaml file so other future contributors won't mess up with this

File: dhall-json/src/Dhall/JSON.hs [hunk 6]
```diff
@@ -213,31 +213,31 @@ module Dhall.JSON (
...
+import Dhall.Map (Map)
 import Options.Applicative (Parser)
 import Prelude hiding (getContents)
 
-import qualified Data.Aeson                            as Aeson
-import qualified Data.Foldable                         as Foldable
-import qualified Data.HashMap.Strict                   as HashMap
+import qualified Data.Aeson as Aeson
+import qualified Data.Foldable as Foldable
+import qualified Data.HashMap.Strict as HashMap
```
Comment (sjakobi) [inline dhall-json/src/Dhall/JSON.hs:233]: It's just a style thing, but this "unalignment" IMHO slightly hurts readability by making the qualified names slightly harder to find.

File: dhall-yaml/src/Dhall/Yaml.hs [hunk 7]
```diff
@@ -51,26 +51,23 @@ jsonToYaml
     -> Bool
     -> ByteString
 jsonToYaml json documents quoted =
+  let encoder = Data.YAML.Aeson.encodeValue' schemaEncoder YT.UTF8 in
```
Comment (sjakobi) [inline dhall-yaml/src/Dhall/Yaml.hs:54]: (Minor style issue): Since there's already a  `where` clause, I would find it hard to decide whether to add the next definition there or as a let-binding. I'd suggest defining `encoder` in the `where`-clause therefore.

File: dhall-yaml/tasty/Main.hs [hunk 8]
```diff
@@ -24,34 +25,57 @@ main = do
...
-    Test.Tasty.testGroup prefix
-        [ testCase Dhall.Yaml.dhallToYaml "HsYAML"
-        , testCase Dhall.JSON.Yaml.dhallToYaml "aeson-yaml"
-        ]
+testDhallToYaml :: Options -> String -> TestScope -> TestTree
+testDhallToYaml options prefix testScope =
+    Test.Tasty.testGroup prefix (
+        let hsYamlTest = testCase Dhall.Yaml.dhallToYaml "HsYAML"
+            hsAesonYamlTest = testCase Dhall.JSON.Yaml.dhallToYaml "aeson-yaml"
+        in
```
Comment (sjakobi) [inline dhall-yaml/tasty/Main.hs:73]: As above, I'd suggest extending the `where`-clause instead.

File: dhall-json/src/Dhall/JSON.hs (hunk 6 above)
Comment (german1608) [reply dhall-json/src/Dhall/JSON.hs:233]: By setting on .stylish-haskell.yaml file `pad_module_names: true` I get your desired result:
```diff
- import qualified Data.Aeson as Aeson
- import qualified Data.Foldable as Foldable
- import qualified Data.HashMap.Strict as HashMap
+ import qualified Data.Aeson                            as Aeson
+ import qualified Data.Foldable                         as Foldable
+ import qualified Data.HashMap.Strict                   as HashMap
```
But other non-qualified import lists gets affected:
```diff
- import Control.Applicative (empty, (<|>))
- import Control.Exception (Exception, throwIO)
- import Control.Monad (guard)
+ import Control.Applicative       (empty, (<|>))
+ import Control.Exception         (Exception, throwIO)
+ import Control.Monad             (guard)
```

Let me know if you're okay with this or not so I deletee .stylish-haskell yaml and defintely turn off my auto-formatting plugin :sweat_smile:

Comment (sjakobi) [reply dhall-json/src/Dhall/JSON.hs:233]: That looks pretty nice to me! :)

@Gabriel439 what do you think?

Comment (Gabriel439) [reply dhall-json/src/Dhall/JSON.hs:233]: Are the qualified and non-qualified imports padded separately?

Comment (german1608) [reply dhall-json/src/Dhall/JSON.hs:233]: @Gabriel439 to answer your question, with current settings (`align: group`) it formats everything in group of imports, using longest line as a basis for that. (example below)

I'm doing some tests and auto-formatting of imports is really opinionated.

The only way to automatically avoid non-qualified import module names to have the padding of qualified space is by having them in separate groups. For example,

```haskell
import A.B (fun1, fun2)
import C.D.E (fun3, fun4)

import qualified F.G as FG
import qualified G.H.C as GHC
import H.I (fun5, fun6)
```
will format to this:
```haskell
import A.B   (fun1, fun2)
import C.D.E (fun3, fun4)

import qualified F.G   as FG
import qualified G.H.C as GHC
import           H.I   (fun5, fun6)
```

There is no available setting related to avoid this result. But if we place imports this way:

```haskell
import A.B (fun1, fun2)
import C.D.E (fun3, fun4)
import H.I (fun5, fun6)

import qualified F.G as FG
import qualified G.H.C as GHC
```

stylish-haskell will format them this way:

```haskell
import A.B   (fun1, fun2)
import C.D.E (fun3, fun4)
import H.I   (fun5, fun6)

import qualified F.G   as FG
import qualified G.H.C as GHC
```

which is the desired format. So we will need to have qualified and non-qualified imports separate to get our desired result

Comment (Gabriel439) [reply dhall-json/src/Dhall/JSON.hs:233]: Alright, if the imports are grouped for alignment purposes, then I prefer `pad_module_names: true`

Comment (german1608) [reply dhall-json/src/Dhall/JSON.hs:233]: Ok cool, I'll update it then.

File: dhall-yaml/src/Dhall/Yaml.hs [hunk 9]
```diff
@@ -54,25 +54,22 @@ jsonToYaml json documents quoted =
...
-        isBoolString
-          | Text.length s > 5 = False
-          | otherwise =
-            case Text.toLower s of
-              "true" -> True
-              "false" -> True
-              _ -> False
+        -- For backwards compatibility with YAML 1.1, we need to add the following to the set of boolean values:
+        -- https://yaml.org/type/bool.html
+        isBoolString = Text.length s <= 5 &&
```
Comment (sjakobi) [inline dhall-yaml/src/Dhall/Yaml.hs:68]: I had been wondering whether taking the `length` of any string we check might itself be a performance problem – `Text.length` is O(n) after all.

Comment (sjakobi) [reply dhall-yaml/src/Dhall/Yaml.hs:68]: (Oops, I clicked "submit" too early.)

`text` has a rewrite rule that uses the `compareLength` function, which [IIUC](https://github.com/haskell/text/issues/284) should be O(5) in this case.

Comment (patrickmn) [reply dhall-yaml/src/Dhall/Yaml.hs:68]: Good to know.

I need to read/understand how Text is implemented. I had assumed a strict Text was just struct { arrayPtr, length } and that `length` was O(1)
