### PR TITLE
Resolves #1408: Add more detail in `--explain` when `toMap` has the w…

### LINKED ISSUE #1408: toMap expects a record value
The error message for `toMap {}` is confusing:

```
$ echo 'toMap {}' | dhall

Use "dhall --explain" for detailed errors

Error: ❰toMap❱ expects a record value

1│ toMap {}

(stdin):1:1
```

Proposal: Add `Did you mean 'toMap {=}'? '{}' is the empty record *type*, and '{=}' is the empty record *value*.`

### PR DESCRIPTION
**Pull request by mjgpy3**
…rong type.

Specifically, add common reason of using `{}` for record value.

For example,
``` shell
echo 'toMap {}' | ~/.local/bin/dhall
```

Outputs

```
Error: ❰toMap❱ expects a record value

Explanation: You can apply ❰toMap❱ to any homogenous record, like this:         
                                                                                
                                                                                
    ┌─────────────────────────────────────────────────────────────────────┐     
    │ let record = { one = 1, two = 2 }                                   │     
    │ in  toMap record : List { mapKey : Text, mapValue : Natural}        │     
    └─────────────────────────────────────────────────────────────────────┘     
                                                                                
                                                                                
... but the argument to ❰toMap❱ must be a record and not some other type.       
                                                                                
Some common reasons why you might get this error:                               
                                                                                
● You accidentally provide an empty record type instead of an empty record when 
  using ❰toMap❱:                                                                
                                                                                
                                                                                
    ┌───────────────────────────────────────────────────────┐                   
    │ toMap {} : List { mapKey : Text, mapValue : Natural } │                   
    └───────────────────────────────────────────────────────┘                   
            ⇧                                                                   
            This should be ❰{=}❱ instead                                        

────────────────────────────────────────────────────────────────────────────────

1│ toMap {}

(stdin):1:1
```

### CODE REVIEW

File: dhall/src/Dhall/TypeCheck.hs [hunk 1]
```diff
@@ -3374,7 +3374,19 @@ prettyTypeMessage (MustMapARecord _expr0 _expr1) = ErrorMessages {..}
...
+        \... but the argument to ❰toMap❱ must be a record and not some other type.       \n\
+        \                                                                                \n\
+        \Some common reasons why you might get this error:                               \n\
+        \                                                                                \n\
+        \● You accidentally provide an empty record type instead of an empty record when \n\
+        \  using ❰toMap❱:                                                                \n\
+        \                                                                                \n\
+        \                                                                                \n\
+        \    ┌──────────┐                                                                \n\
+        \    │ toMap {} │                                                                \n\
```
Comment (sjakobi) [inline dhall/src/Dhall/TypeCheck.hs]: Can you add a type annotation? Otherwise it will still not typecheck after replacing `{}` with `{=}`.

Comment (mjgpy3) [reply dhall/src/Dhall/TypeCheck.hs]: @sjakobi sure thing, good point!

**Comment by mjgpy3** [comment]
@sjakobi done and output is updated in description above.
