### PR TITLE
Fix indentation for multiline Some-, toMap- and merge-expressions

### LINKED ISSUE #1376: Missing indentation when formatting merge- and toMap expressions
```
$ echo 'merge tttttttttttttttttttttttttttttttttttttttttttttt uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu' | dhall format
merge
tttttttttttttttttttttttttttttttttttttttttttttt
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu
```

This should be formatted as

```
merge
  tttttttttttttttttttttttttttttttttttttttttttttt
  uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu
```

```
$ echo 'toMap rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr' | dhall format
toMap
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
```

This should be formatted as

```
toMap
  rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
```

This "regression" was introduced in https://github.com/dhall-lang/dhall-haskell/commit/75e6cc5ca7dccf4c8d5831f0aaa664fc3400f060.

### PR DESCRIPTION
**Pull request by sjakobi**
The loss of indentation for toMap and merge was due to
75e6cc5ca7dccf4c8d5831f0aaa664fc3400f060. I have included Some for
consistency.

Fixes #1376.

Also improve format test failure messages

### CODE REVIEW

File: dhall/src/Dhall/Pretty/Internal.hs [hunk 1]
```diff
@@ -837,22 +838,20 @@ prettyCharacterSet characterSet expression =
...
+        App a b           -> f (prettyApplicationExpression a) [b]
+        Some a            -> f (builtin "Some") [a]
+        ToMap a Nothing   -> f (keyword "toMap") [a]
+        Merge a b Nothing -> f (keyword "merge") [a, b]
+        Note _ b          -> prettyApplicationExpression b
+        e                 -> prettyImportExpression e
       where
-        result = enclose' "" "" " " "" (reverse (docs a0))
-
-        docs (App  a b) = ( prettyImportExpression b, Pretty.indent 2 (prettyImportExpression b) ) : docs a
```
Comment (sjakobi) [inline dhall/src/Dhall/Pretty/Internal.hs]: My refactoring broke the formatting of application-expressions where the first arguments are short:

```
f x
  rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
```

should be

```
f
  x
  rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
```

I'll try again

Comment (sjakobi) [reply dhall/src/Dhall/Pretty/Internal.hs]: What I don't understand is why record fields are still formatted correctly:

```
{ a =
    f
      x
      rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
}
```
