### PR TITLE
Document Dhall support for caching protected imports

### LINKED ISSUE #1234: Tutorial section "Import integrity" differs from observed behavior
Dhall.Tutorial describes in the section about [Import integrity](http://hackage.haskell.org/package/dhall-1.25.0/docs/Dhall-Tutorial.html#g:16) a way to check that an imported value stays constant.
It shows an example that triggers "Error: Import integrity check failed" because of a hash mismatch when the imported value is changed.

However, with the current caching behavior, this doesn't always seem to happen.
Once the "correct" import has been evaluated once, changing the imported value has no effect anymore because the hashed value is looked up from the cache, if I understand it correctly.
According to my tests, this happened between 1.16.1 and 1.17.0 .

I assume that this is the desired behavior now and that the tutorial hasn't been updated to reflect this change yet.
If that is the case, is there a way to get similar checks in the current version, as the tutorial demonstrates?
It would be useful to use these hash annotations as part of a "snapshot test", to see if an imported value behaves the same after a refactoring.
Perhaps the cache-reading could be disabled by some flag?

([Here is the relevant section in the Dhall.Tutorial source](https://github.com/dhall-lang/dhall-haskell/blob/8c3db821dbc0ad8cfd01d09a58e88126bda717ab/dhall/src/Dhall/Tutorial.hs#L1520))

### PR DESCRIPTION
**Pull request by Gabriel439**
Fixes #1234

### CODE REVIEW

File: dhall/src/Dhall/Tutorial.hs [hunk 1]
```diff
@@ -1550,8 +1550,39 @@ import Dhall
...
+-- > 1
+--
+-- Subsequent attempts to resolve the same import will automatically retrieve
+-- the import from the cache.  This matters less for local imports, but comes in
+-- handy for remote imports to avoid redownloading them.
+--
+-- The local cache takes precedence when resolving imports, so changing the
+-- original import afterwards will have no affect until you update the hash.
+-- From Dhall's point of view, the hash is the true address and the file path
+-- is just a suggestion for how to obtain the import if it's not already cached.
```
Comment (sjakobi) [inline dhall/src/Dhall/Tutorial.hs]: It's good to see the relative importance of the hash and the file path spelled out like that! :+1:
