### PR TITLE
Resolve #1451: fix `format --check` given STDIN input.

### LINKED ISSUE #1451: `dhall format --check` tries to read stdin twice
```
$ echo '1 + 1' | dhall format --check
dhall: <stdin>: hGetBuffering: illegal operation (handle is closed)
```

### PR DESCRIPTION
**Pull request by mjgpy3**
I'm not really sure if this is the "best" approach so let me know if you
know a way to simplify this.

The issue was that `getExpressionAndHeader` was doing a second
`IO.getContents` (thus reading STDIN twice).

### CODE REVIEW

File: dhall/src/Dhall/Util.hs [hunk 1]
```diff
@@ -122,13 +125,21 @@ data Censor = NoCensor | Censor
 -- | Path to input
 data Input = StandardInput | InputFile FilePath
 
+-- | Path to input or raw input text, necessary since we can't read STDIN twice
+data InputOrTextFromStdin = PathTo Input | StdinText Text
```
Comment (sjakobi) [inline dhall/src/Dhall/Util.hs]: `PathTo StandardInput` seems like a bit of a strange combination to me. How about
```suggestion
data InputOrTextFromStdin = Input_ Input | StdinText Text
```

Comment (mjgpy3) [reply dhall/src/Dhall/Util.hs]: Done.
