### PR TITLE
Don't panic on `Text/replace ""`

### LINKED ISSUE #2181: `Text/replace ""` triggers "Compiler bug"
At the current `master`:

```
$ cabal run -w ghc-8.10.4 dhall:dhall -- repl
Up to date
Welcome to the Dhall v1.38.1 REPL! Type :help for more information.
⊢ Text/replace ""

Error: Compiler bug                                                        
                                                                                
An ill-typed expression was encountered during normalization.                   
Explanation: This error message means that there is a bug in the Dhall compiler.
You didn't do anything wrong, but if you would like to see this problem fixed   
then you should report the bug at:                                              
                                                                                
https://github.com/dhall-lang/dhall-haskell/issues                              

CallStack (from HasCallStack):
  error, called at src/Dhall/Eval.hs:1201:13 in dhall-1.38.1-inplace:Dhall.Eval
```

This was found by the "everything well-typed should normalize" test in https://github.com/dhall-lang/dhall-haskell/pull/2154#issuecomment-836700787.

### PR DESCRIPTION
**Pull request by Gabriel439**
Fixes #2181

### CODE REVIEW

File: dhall/src/Dhall/Eval.hs [hunk 1]
```diff
@@ -603,33 +605,38 @@ eval !env t0 =
...
-                                            (Text.replace
-                                                needleText
-                                                replacementText
-                                                haystackText
-                                            )
+                let hLamInfo = case needle of
+                        VTextLit (VChunks [] "") -> TextReplaceEmpty
+                        _                        -> Prim
+
+                in  VHLam hLamInfo $ \replacement ->
```
Comment (sjakobi) [inline dhall/src/Dhall/Eval.hs:612]: So that's how you include the lambda in the `TextReplaceEmpty` case! :) I hadn't figured that out.

**Review by sjakobi — APPROVED** [review]
Looks great! Ideally this should be merged together with the added tests from https://github.com/dhall-lang/dhall-lang/pull/1172, but it doesn't matter much.
